import Link from "next/link";

const tools = [
  {
    href: "/internal/email-preview?email=beta-invite",
    label: "Email Preview",
    description: "Preview React email templates and internal notices, including the beta invite.",
  },
  {
    href: "/internal/beta-invite-preview",
    label: "Beta Invite Preview",
    description: "Focused preview page for the beta invite email only.",
  },
  {
    href: "/internal/unsubscribe-preview",
    label: "Unsubscribe Preview",
    description: "Generate a valid preferences token and open the live unsubscribe page owned by dotzcash_main.",
  },
  {
    href: "/internal/banner-preview",
    label: "Banner Preview",
    description: "Large poster/banner editor with QR, text, asset upload, and export controls.",
  },
  {
    href: "/internal/link-previews",
    label: "Link Preview QA",
    description: "Inspect OG/Twitter preview cards generated by the real image routes.",
  },
  {
    href: "/internal/text-splitter",
    label: "Text Splitter",
    description: "Split, edit, and reassemble source text interactively.",
  },
  {
    href: "/internal/quotepost",
    label: "Quotepost",
    description: "Local-only quote graphic composer for batch content work.",
  },
  {
    href: "/internal/blockinfo-post",
    label: "Blockinfo Post",
    description: "Generate a zebra_stats image post, save it, upload it, and post it to Telegram, X, or both.",
  },
  {
    href: "/internal/referinfo-post",
    label: "Referinfo Post",
    description: "Generate the weekly referral-intelligence thread, preview each card, and post the queue to Telegram, X, or both.",
  },
  {
    href: "/internal/reserveinfo-post",
    label: "Reserveinfo Post",
    description: "Preview the weekly reserved-names queue and publish its persistent Telegram and X pages.",
  },
  {
    href: "/internal/ens-outreach",
    label: "ENS Outreach",
    description: "Build manual X outreach drafts for ENS-priority protected names, including popup assets.",
  },
] as const;

export default function InternalToolsIndexPage() {
  return (
    <main className="mx-auto w-full max-w-6xl px-6 py-10">
      <header className="mb-8 rounded-2xl border p-6" style={{ background: "var(--tool-panel-bg)", borderColor: "var(--tool-panel-border)" }}>
        <p className="text-xs font-semibold uppercase tracking-[0.18em] text-fg-muted">Authenticated Access</p>
        <h1 className="mt-2 text-3xl font-bold tracking-tight text-fg-heading">Internal Tools</h1>
        <p className="mt-3 max-w-3xl text-sm leading-6 text-fg-muted">
          Preview, QA, and asset-generation utilities that stay off the production branch.
          Use this page as the protected sitemap for internal routes.
        </p>
      </header>

      <div className="grid gap-4 md:grid-cols-2">
        {tools.map((tool) => (
          <Link
            key={tool.href}
            href={tool.href}
            className="rounded-2xl border p-5 transition-colors hover:border-fg-muted"
            style={{ background: "var(--tool-panel-bg)", borderColor: "var(--tool-panel-border)" }}
          >
            <div className="text-sm font-semibold text-fg-heading">{tool.label}</div>
            <div className="mt-1 text-xs text-fg-muted">{tool.href}</div>
            <div className="mt-3 text-sm leading-6 text-fg-body">{tool.description}</div>
          </Link>
        ))}
      </div>
    </main>
  );
}
